### ISSUE TITLE
Add "missing" Abe API calls

### ISSUE THREAD

**Issue by barnumbirr** [alferz/worldcoin-abe#2]
Hi there,

compared to [the Darkcoin blockexplorer](http://explorer.darkcoin.io/q) `wdcexplorer.com` is missing three rather important API calls:
- addr  - returns the full address having the given firstbits.
- fb - returns an address's firstbits.
- nethash - shows statistics about difficulty and network power.

Would it be possible to add those? Without at least the `nethash`call there is no way to return the  current block reward or the network hashrate.

Cheers.

**EDIT:** I've just seen [that you removed those functions in the Abe source code](https://github.com/alferz/worldcoin-abe/commit/055758a6c3fd0fd2b93ceada0dc96e2a04dcd393). Would it be possible for you to revert those specific modifications?

**Comment by alferz** [comment]
Hey mrsmn - as for addr and fb I ended up removing those because it appears you must specify the use_firstbits flag when building the PGDB for the first time, which I neglected to do. I considered rebuilding the DB but couldn't figure out what the use case was for using first bits in the first place. Is it to allow another tool to discover a vanity address or something else? Is there a big need for this? If so I could rebuild the DB but that will take up precious CPU and memory so just want to make sure there is a use case. And if you try an address on the Darkcoin Explorer's /q/fb/ page, like [this one](http://explorer.darkcoin.io/q/fb/XnSZtxz4ahb5vpsRHLSeFB7axgnZ6zJ3Kr) it appears they arent properly supporting these two either.

As for nethash - I removed that one because by default it takes a long time to load and seems pretty inefficient - hitting /q/nethash makes it scan the entire blockchain, over 1.95M+ blocks and report data for every 144 blocks which I'm not really seeing a use case for. I could modify this function to restrict the data to say 100K blocks at a time to improve performance. But it seems the most interesting info is the current block reward and hashrate. Is there any other info in nethash you think is worth exposing? I think it would be best to write a quick function to report the current reward and hashrate as for instance, /q/hashrate and /q/currentreward which another service could then consume. What do you think?

**Comment by barnumbirr** [comment]
Hi there @alferz,

very simply put, firstbits consists of shortening a cryptocurrency address. If you want more details about it, [you can find some here](https://en.bitcoin.it/wiki/Firstbits). I don't think there is a particularly huge need for it, especially if you have to rebuild the whole DB. Like you've pointed out, [the Darkcoin explorer doesn't support it either](http://explorer.darkcoin.io/q/fb).

The nethash on the other other, is in my opinion quite a useful API call even though it's quite ressource hungry. If you're up for it you could enable `nethash` but also create a `hashrate` and `reward` calls so people don't have to scan the entire blockchain to get the information. It would allow people to easily get the `hashrate/reward` but still get a huge amount of information if they need to with `nethash`.

Thank you for your time, it's great having people like you in the WDC community. Don't hesitate to get in touch if you need some help.

Cheers.
